### PR TITLE
Switch meilisearch-migration repository from bidouwa to alallema

### PR DESCRIPTION
**Pull request by alallema**

### CODE REVIEW

**Review by brunoocasali — APPROVED** [review]
Awesome! 🎉

**Comment by curquiza** [comment]
Nice update!

**Comment by curquiza** [comment]
Would be better to have the official approval of @bidoubiwa before any merge for traceability, even if I supposed you discussed this in meeting 🙃

**Comment by alallema** [comment]
Yes, we discuss this at the weekly meeting, but you are right I should have asked her for it.

**Pull request merged**
