### PR TITLE
Add the integration team demo resource

### PR DESCRIPTION
**Pull request by curquiza**
Add a small guide to describe what are the only demos the integration team owns.

### CODE REVIEW

**Review by alallema — APPROVED** [review]
LGTM! 🎉

**Comment by bidoubiwa** [comment]
We should add that I'm maintaining the geosearch playground in the instant-meilisearch repo. Not sure how this integrates with the structure of your page :/

**Comment by curquiza** [comment]
@bidoubiwa @alallema I changed the guide according to the new index (word_cities). I re-request you.

**Review by bidoubiwa — APPROVED** [review]
LGTM 🔥

**Review by alallema — APPROVED** [review]
LGTM! 🎉

**Pull request merged**
